# Generated by Django 4.2.1 on 2025-11-08 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_movie_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hello",
        ),
    ]
